import fs from "fs";
import path from "path";
import AdmZip from "adm-zip";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function generateReactNativeProjectZip({ prompt, srcDir, zipPath, appId }){
  fs.mkdirSync(srcDir, { recursive: true });
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
  const system = `You are a code generator that outputs a complete minimal React Native (Expo) project.
Output ONLY valid JSON array: [{"path":"filePath","content":"fileContent"}].
Constraints:
- Expo managed workflow; runnable with 'npx expo start'
- Include: package.json, app.json, App.js, .gitignore, README.md
- Functional components + hooks. Avoid native modules.`;
  const user = `User prompt: ${prompt}\nApp name: MobileDev App ${appId}`;
  const result = await model.generateContent([{text: system},{text:user}]);
  const text = result.response.text();
  let files;
  try { files = JSON.parse(text); }
  catch {
    files = [
      { path: "package.json", content: JSON.stringify({
        name: "mobiledev-app-"+appId, version:"1.0.0", private:true,
        main:"node_modules/expo/AppEntry.js",
        scripts:{ start:"expo start", android:"expo run:android", ios:"expo run:ios" },
        dependencies:{ expo:"~51.0.0", "expo-status-bar":"~1.12.1", react:"18.2.0", "react-native":"0.75.0" }
      }, null, 2)},
      { path: "app.json", content: JSON.stringify({ expo:{ name:"MobileDev App", slug:"mobiledev-app-"+appId, sdkVersion:"51.0.0"}}, null,2)},
      { path: "App.js", content: "export default function App(){return null;}" },
      { path: ".gitignore", content: "node_modules\n.expo\n.expo-shared\n" },
      { path: "README.md", content: "# MobileDev App\nGenerated by AI." }
    ];
  }
  const cloudbuild = `steps:
  - name: gcr.io/cloud-builders/npm
    args: ["ci"]
  - name: gcr.io/cloud-builders/npm
    args: ["install", "-g", "expo-cli"]
  - name: gcr.io/cloud-builders/npm
    args: ["run", "prebuild"]
    env: ["EXPO_NO_DOCTOR=1"]
  - name: gcr.io/android-ci-images/android:34-node18
    entrypoint: bash
    args:
      - "-lc"
      - |
        set -e
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp","android/app/build/outputs/apk/debug/app-debug.apk","gs://$BUCKET/users/$UID/apps/$APP_ID/outputs/app-debug.apk"]
artifacts:
  objects:
    location: gs://$BUCKET/users/$UID/apps/$APP_ID/outputs/
    paths: ["android/app/build/outputs/**/*.apk"]
options: { logging: CLOUD_LOGGING_ONLY }
`;
  files.push({ path:"cloudbuild.yaml", content: cloudbuild });

  for(const f of files){
    const full = path.join(srcDir, f.path);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, f.content, "utf8");
  }
  const Adm = new AdmZip();
  Adm.addLocalFolder(srcDir);
  Adm.writeZip(zipPath);
  return files;
}
